title:              Clean Blog
email:              jongwhoa.lee@gmail.com
description:        A Blog Theme by Start Bootstrap
author:             willook
baseurl:            ""
url:                "https://willook.github.io"

# Social Profiles
github_username:    willook
linkedin_username:  willook

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
